---
title: "Cluster Analysis Clean"
author: "Rob Patro"
date: "5/27/2021"
output: 
    html_document:
        keep_md: true
---

This script is used for exploring the minimum number of cells that results in the discovery of the two distinct cone PhR clusters. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Functions used in the analysis 

```{r}
suppressPackageStartupMessages({
    library(devtools)
    library(ggplot2)
    library(SingleCellExperiment)
    library(Seurat)
    library(Matrix)
    library(DropletUtils)
})
set.seed(1234)
dir.create("figures",recursive = TRUE, showWarnings = FALSE)

```


```{r}
#' Read alevin-fry quantifications into a SingleCellExperiment object
load_fry <- function(frydir, which_counts = c('S', 'A'), verbose = FALSE) {
  suppressPackageStartupMessages({
    library(rjson)
    library(Matrix)
    library(SingleCellExperiment)
  })
  
  # read in metadata
  meta_info <- fromJSON(file = file.path(frydir, "meta_info.json"))
  ng <- meta_info$num_genes
  usa_mode <- meta_info$usa_mode
  
  if (usa_mode) {
    if (length(which_counts) == 0) {
      stop("Please at least provide one status in 'U' 'S' 'A' ")
    }
    if (verbose) {
      message("processing input in USA mode, will return ", paste(which_counts, collapse = '+'))
    }
  } else if (verbose) {
    message("processing input in standard mode, will return spliced count")
  }

  # read in count matrix
  af_raw <- readMM(file = file.path(frydir, "alevin", "quants_mat.mtx"))
  # if usa mode, each gene gets 3 rows, so the actual number of genes is ng/3
  if (usa_mode) {
    if (ng %% 3 != 0) {
      stop("The number of quantified targets is not a multiple of 3")
    }
    ng <- as.integer(ng/3)
  }
  
  # read in gene name file and cell barcode file
  afg <- read.csv(file.path(frydir, "alevin", "quants_mat_cols.txt"), 
                  strip.white = TRUE, header = FALSE, nrows = ng, 
                  col.names = c("gene_ids"), row.names = 1)
  afc <- read.csv(file.path(frydir, "alevin", "quants_mat_rows.txt"), 
                  strip.white = TRUE, header = FALSE,
                  col.names = c("barcodes"), row.names = 1)

  # if in usa_mode, sum up counts in different status according to which_counts
  if (usa_mode) {
    rd <- list("S" = seq(1, ng), "U" =  seq(ng + 1, 2 * ng),
               "A" =  seq(2 * ng + 1, 3 * ng))
    o <- af_raw[, rd[[which_counts[1]]], drop = FALSE]
    for (wc in which_counts[-1]) {
      o <- o + af_raw[, rd[[wc]], drop = FALSE]
    }
  } else {
    o <- af_raw
  }
  
  # create SingleCellExperiment object
  sce <- SingleCellExperiment(list(counts = t(o)),
                              colData = afc,
                              rowData = afg
  )
  sce
}
```


```{r}
get_clusters <- function(seurat_obj, do_scale=TRUE) {
  seurat_obj[["percent.mt"]] <- PercentageFeatureSet(seurat_obj, pattern = "^mt-")
  violin_plot <- VlnPlot(seurat_obj, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
  plot1 <- FeatureScatter(seurat_obj, feature1 = "nCount_RNA", feature2 = "percent.mt")
  plot2 <- FeatureScatter(seurat_obj, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
  feat_plot <- plot1 + plot2
  
  seurat_obj_filt <- subset(seurat_obj, subset = nFeature_RNA < 6000 & nCount_RNA < 25000)
  seurat_obj_filt <- subset(seurat_obj_filt, subset = nFeature_RNA > 200 & nCount_RNA < 15000 & percent.mt < 30)
  
  seurat_obj_filt <- NormalizeData(seurat_obj_filt, normalization.method = "LogNormalize", scale.factor = 10000)

  seurat_obj_filt <- FindVariableFeatures(seurat_obj_filt, selection.method = "vst", nfeatures = 2000)
  
  all.genes <- rownames(seurat_obj_filt)
 
  seurat_obj_filt <- ScaleData(seurat_obj_filt, features = all.genes, do.scale=do_scale)
  
  seurat_obj_filt <- RunPCA(seurat_obj_filt, features = VariableFeatures(object = seurat_obj_filt))
  pca_plot <- DimPlot(seurat_obj_filt, reduction = "pca")

  seurat_obj_filt <- FindNeighbors(seurat_obj_filt, dims = 1:20)
  
  seurat_obj_filt_0.9 <- FindClusters(seurat_obj_filt, resolution = 0.9)
  seurat_obj_filt_1.2 <- FindClusters(seurat_obj_filt, resolution = 1.2)
  
  seurat_obj_filt_0.9 <- RunTSNE(seurat_obj_filt_0.9, dims = 1:20)
  seurat_obj_filt_1.2 <- RunTSNE(seurat_obj_filt_1.2, dims = 1:20)
  
  tsne0.9 <- DimPlot(seurat_obj_filt_0.9, reduction = "tsne", label=TRUE,repel=TRUE, label.size = 8) # + theme(axis.title.y = element_blank(), axis.title.x = element_blank())
  tsne1.2 <- DimPlot(seurat_obj_filt_1.2, reduction = "tsne", label=TRUE,repel=TRUE, label.size = 8) # + theme(axis.title.y = element_blank(), axis.title.x = element_blank())
  
  # seurat_obj_filt_0.9.markers <- FindAllMarkers(seurat_obj_filt_0.9, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)    
  # seurat_obj_filt_1.2.markers <- FindAllMarkers(seurat_obj_filt_1.2, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
  
  feat_genes <- c("exorh", "gnat1", "gngt1", "gnat2", "gngt2a", "col14a1b", "opn1lw1", "parietopsin", "asip2b", "rpe65a", "dkk3b", 
                  "fabp7b", "elavl4", "cart3", "gng8", "kiss1", "dcn", "igfbp5b", "cahz", "hbaa1", "ccr9a", "il4", "cd74a", "apoc1", 
                  "kdrl", "plvapa", "epcam", "icn2")
  dotplot_0.9 <- DotPlot(object = seurat_obj_filt_0.9, dot.scale = 3, features = feat_genes) + theme(axis.text.x = element_text(angle = 50, hjust = 1, vjust = 1), axis.title.y = element_blank(), axis.title.x = element_blank())
  dotplot_1.2 <- DotPlot(object = seurat_obj_filt_1.2, dot.scale = 3, features = feat_genes) + theme(axis.text.x = element_text(angle = 50, hjust = 1, vjust = 1), axis.title.y = element_blank(), axis.title.x = element_blank())
  
  retlist <- list("violin_plot" = violin_plot, 
                  "feat_plot" = feat_plot, 
                  "pca_plot" = pca_plot, 
                  "tsne0.9" = tsne0.9,
                  "tsne1.2" = tsne1.2, 
                  "dotplot0.9" = dotplot_0.9, 
                  "dotplot1.2" = dotplot_1.2, 
                  "obj0.9" = seurat_obj_filt_0.9, 
                  "obj1.2" = seurat_obj_filt_1.2
                  # ,"markers0.9" = seurat_obj_filt_0.9.markers
                  # ,"markers1.2" = seurat_obj_filt_1.2.markers
                  )
  return(retlist) 
}
```

```{r}
filter_empty <- function(unfiltered_sce, lower=100) {
  br.out <- barcodeRanks(counts(unfiltered_sce))
  e.out <- emptyDrops(counts(unfiltered_sce), lower=lower)
  is.cell <- e.out$FDR <= 0.01
  is.cell[is.na(is.cell)] <- FALSE
  sum(is.cell, na.rm=TRUE)
  filtered_sce <- unfiltered_sce[,is.cell]
  seu <- CreateSeuratObject(counts(filtered_sce), min.cells = 3, min.feature = 200)
  return(seu)
}
```

```{r}
filter_empty_shainer <- function(sce) {
  # parameters / method taken from https://github.com/mstemmer/kb-helper/blob/main/kb_data_to_seurat.Rmd
  tot_counts <- colSums(counts(sce))
  summary(tot_counts)
  bc_rank <- barcodeRanks(counts(sce), lower = 500)
   
  # Remove genes that are not detected and empty droplets
  sce <- sce[, tot_counts > metadata(bc_rank)$inflection]
  dim(sce) # use print() to show output in a for loop
  
  seu <- CreateSeuratObject(counts(sce), min.cells = 3, min.feature = 200)
  return(seu)
}
```


```{r}
gid_to_gname <- read.table('dr_gid_to_gname_fixed.tsv')
```

```{r}
fix_gene_names <- function(sce, gid_to_gname, strip_version=FALSE) {
  if (strip_version) {
    rownames(sce) <- sub("\\.\\d+", "", rownames(sce))
  }
  rownames(sce) <- gid_to_gname$V2[match(rownames(sce), gid_to_gname$V1)]
  return(sce)
}
```

```{r}
load_kb_matrix <- function(matdir) {
  
  bcp <- file.path(matdir, "cells_x_genes.barcodes.txt")
  gnp <- file.path(matdir, "cells_x_genes.genes.txt")
  mp <- file.path(matdir, "cells_x_genes.mtx")
  
  kbc <- read.csv(bcp, strip.white = TRUE, header = FALSE,
                  col.names = c("barcodes"), row.names = 1)
  genes <- read.csv(gnp, strip.white = TRUE, header = FALSE,
                  col.names = c("barcodes"), row.names = 1)
  kbm <- readMM(mp)
  kbme <- SingleCellExperiment(list(counts=t(kbm)), rowData=genes, colData=kbc)
  return(kbme)
}
```


```{r}
feat_genes <- c("exorh", "gnat1", "gngt1", "gnat2", "gngt2a", "col14a1b", "opn1lw1", "parietopsin", "asip2b", "rpe65a", "dkk3b", 
                "fabp7b", "elavl4", "cart3", "gng8", "kiss1", "dcn", "igfbp5b", "cahz", "hbaa1", "ccr9a", "il4", "cd74a", "apoc1", 
                "kdrl", "plvapa", "epcam", "icn2")
```



# fry

```{r}
set.seed(1234)

quant_sa_unfilt <- load_fry('fry_results/fry_unfilt_quant_usa_cr-like', which_counts=c('S','A'))
quant_sa_unfilt <- fix_gene_names(quant_sa_unfilt, gid_to_gname)
ranks = order(colSums(counts(quant_sa_unfilt)),decreasing = TRUE)

```



```{r}
# 4026y 4025y 4024n
seu <- CreateSeuratObject(counts(quant_sa_unfilt)[,ranks[1:4025]],min.cells = 3,  min.feature = 200)

af_unfilt_shainer_res <- get_clusters(seu)
af_unfilt_shainer_res$dotplot0.9 
```

```{r}
gene_af_red_cone2 = FindMarkers(af_unfilt_shainer_res$obj0.9,ident.1 = "12", only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
gene_af_red_cone2 = rownames(gene_af_red_cone2)[gene_af_red_cone2$p_val_adj < 0.05]
gene_af_pt_cone2 = FindMarkers(af_unfilt_shainer_res$obj0.9,ident.1 = "16", only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
gene_af_pt_cone2 = rownames(gene_af_pt_cone2)[gene_af_pt_cone2$p_val_adj < 0.05]

length(gene_af_pt_cone2)
length(gene_af_red_cone2)
```



# kb

```{r}
set.seed(1234)

kbc <- read.csv('kb_results/cells_x_genes.barcodes.txt', 
                  strip.white = TRUE, header = FALSE,
                  col.names = c("barcodes"), row.names = 1)
genes <- read.csv('kb_results/cells_x_genes.genes.txt', 
                  strip.white = TRUE, header = FALSE,
                  col.names = c("barcodes"), row.names = 1)
kbm <- readMM('kb_results/cells_x_genes.mtx')
kbme <- SingleCellExperiment(list(counts=t(kbm)), rowData=genes, colData=kbc)
kbme <- fix_gene_names(kbme,gid_to_gname, strip_version=TRUE)
ranks = order(colSums(counts(kbme)),decreasing = TRUE)

```



```{r}
# 4030y 4029y 4028y 4027y 4026n

seu <- CreateSeuratObject(counts(kbme)[,ranks[1:4027]],min.cells = 3,  min.feature = 200)

kb_unfilt_shainer_res <- get_clusters(seu)
kb_unfilt_shainer_res$dotplot0.9 
```

```{r}
gene_kb_red_cone = FindMarkers(kb_unfilt_shainer_res$obj0.9,ident.1 = "17", only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
gene_kb_red_cone = rownames(gene_kb_red_cone)[gene_kb_red_cone$p_val_adj < 0.05]
gene_kb_pt_cone = FindMarkers(kb_unfilt_shainer_res$obj0.9,ident.1 = "19", only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
gene_kb_pt_cone = rownames(gene_kb_pt_cone)[gene_kb_pt_cone$p_val_adj < 0.05]

```


Process the STARsolo unfiltered output.

```{r, results='hide'}
set.seed(1234)

ss_unfilt <- Read10X('st_results/1mm/raw')
ss_unfilt <- SingleCellExperiment(list(counts = ss_unfilt),
                              colData = colnames(ss_unfilt),
                              rowData = rownames(ss_unfilt))
ranks = order(colSums(counts(ss_unfilt)),decreasing = TRUE)

```

```{r}
# 4004n 4005n 4006n 4010y 4008n 4009y
seu <- CreateSeuratObject(counts(ss_unfilt)[,ranks[1:4009]],min.cells = 3,  min.feature = 200)

ss_unfilt_shainer_res <- get_clusters(seu)
ss_unfilt_shainer_res$dotplot0.9 
```


```{r, results='hide'}
set.seed(1234)

ss_unfilt <- Read10X('st_results/1mmDir/raw')
ss_unfilt <- SingleCellExperiment(list(counts = ss_unfilt),
                              colData = colnames(ss_unfilt),
                              rowData = rownames(ss_unfilt))
ranks = order(colSums(counts(ss_unfilt)),decreasing = TRUE)

```

```{r}
# 4011n 4013y 4012n
seu <- CreateSeuratObject(counts(ss_unfilt)[,ranks[1:4013]],min.cells = 3,  min.feature = 200)

ss_unfilt_shainer_res <- get_clusters(seu)
ss_unfilt_shainer_res$dotplot0.9 
```


```{r, results='hide'}
set.seed(1234)

ss_unfilt <- Read10X('st_results/exact/raw')
ss_unfilt <- SingleCellExperiment(list(counts = ss_unfilt),
                              colData = colnames(ss_unfilt),
                              rowData = rownames(ss_unfilt))
ranks = order(colSums(counts(ss_unfilt)),decreasing = TRUE)

```

```{r}
# 4010y 4008n 4009n
seu <- CreateSeuratObject(counts(ss_unfilt)[,ranks[1:4010]],min.cells = 3,  min.feature = 200)

ss_unfilt_shainer_res <- get_clusters(seu)
ss_unfilt_shainer_res$dotplot0.9 
```


















